package com.example.streamdemo.domain;

/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Insurance extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7231386984193489576L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Insurance\",\"namespace\":\"com.example.streamdemo.domain\",\"fields\":[{\"name\":\"plan\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"company\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"validFrom\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"age\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String plan;
  @Deprecated public java.lang.String company;
  @Deprecated public java.lang.String validFrom;
  @Deprecated public int age;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Insurance() {}

  /**
   * All-args constructor.
   * @param plan The new value for plan
   * @param company The new value for company
   * @param validFrom The new value for validFrom
   * @param age The new value for age
   */
  public Insurance(java.lang.String plan, java.lang.String company, java.lang.String validFrom, java.lang.Integer age) {
    this.plan = plan;
    this.company = company;
    this.validFrom = validFrom;
    this.age = age;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
      case 0: return plan;
      case 1: return company;
      case 2: return validFrom;
      case 3: return age;
      default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
      case 0: plan = (java.lang.String)value$; break;
      case 1: company = (java.lang.String)value$; break;
      case 2: validFrom = (java.lang.String)value$; break;
      case 3: age = (java.lang.Integer)value$; break;
      default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'plan' field.
   * @return The value of the 'plan' field.
   */
  public java.lang.String getPlan() {
    return plan;
  }

  /**
   * Sets the value of the 'plan' field.
   * @param value the value to set.
   */
  public void setPlan(java.lang.String value) {
    this.plan = value;
  }

  /**
   * Gets the value of the 'company' field.
   * @return The value of the 'company' field.
   */
  public java.lang.String getCompany() {
    return company;
  }

  /**
   * Sets the value of the 'company' field.
   * @param value the value to set.
   */
  public void setCompany(java.lang.String value) {
    this.company = value;
  }

  /**
   * Gets the value of the 'validFrom' field.
   * @return The value of the 'validFrom' field.
   */
  public java.lang.String getValidFrom() {
    return validFrom;
  }

  /**
   * Sets the value of the 'validFrom' field.
   * @param value the value to set.
   */
  public void setValidFrom(java.lang.String value) {
    this.validFrom = value;
  }

  /**
   * Gets the value of the 'age' field.
   * @return The value of the 'age' field.
   */
  public java.lang.Integer getAge() {
    return age;
  }

  /**
   * Sets the value of the 'age' field.
   * @param value the value to set.
   */
  public void setAge(java.lang.Integer value) {
    this.age = value;
  }

  /**
   * Creates a new Insurance RecordBuilder.
   * @return A new Insurance RecordBuilder
   */
  public static com.example.streamdemo.domain.Insurance.Builder newBuilder() {
    return new com.example.streamdemo.domain.Insurance.Builder();
  }

  /**
   * Creates a new Insurance RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Insurance RecordBuilder
   */
  public static com.example.streamdemo.domain.Insurance.Builder newBuilder(com.example.streamdemo.domain.Insurance.Builder other) {
    return new com.example.streamdemo.domain.Insurance.Builder(other);
  }

  /**
   * Creates a new Insurance RecordBuilder by copying an existing Insurance instance.
   * @param other The existing instance to copy.
   * @return A new Insurance RecordBuilder
   */
  public static com.example.streamdemo.domain.Insurance.Builder newBuilder(com.example.streamdemo.domain.Insurance other) {
    return new com.example.streamdemo.domain.Insurance.Builder(other);
  }

  /**
   * RecordBuilder for Insurance instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Insurance>
      implements org.apache.avro.data.RecordBuilder<Insurance> {

    private java.lang.String plan;
    private java.lang.String company;
    private java.lang.String validFrom;
    private int age;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.streamdemo.domain.Insurance.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.plan)) {
        this.plan = data().deepCopy(fields()[0].schema(), other.plan);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.company)) {
        this.company = data().deepCopy(fields()[1].schema(), other.company);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.validFrom)) {
        this.validFrom = data().deepCopy(fields()[2].schema(), other.validFrom);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.age)) {
        this.age = data().deepCopy(fields()[3].schema(), other.age);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Insurance instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.streamdemo.domain.Insurance other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.plan)) {
        this.plan = data().deepCopy(fields()[0].schema(), other.plan);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.company)) {
        this.company = data().deepCopy(fields()[1].schema(), other.company);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.validFrom)) {
        this.validFrom = data().deepCopy(fields()[2].schema(), other.validFrom);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.age)) {
        this.age = data().deepCopy(fields()[3].schema(), other.age);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Gets the value of the 'plan' field.
     * @return The value.
     */
    public java.lang.String getPlan() {
      return plan;
    }

    /**
     * Sets the value of the 'plan' field.
     * @param value The value of 'plan'.
     * @return This builder.
     */
    public com.example.streamdemo.domain.Insurance.Builder setPlan(java.lang.String value) {
      validate(fields()[0], value);
      this.plan = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
     * Checks whether the 'plan' field has been set.
     * @return True if the 'plan' field has been set, false otherwise.
     */
    public boolean hasPlan() {
      return fieldSetFlags()[0];
    }


    /**
     * Clears the value of the 'plan' field.
     * @return This builder.
     */
    public com.example.streamdemo.domain.Insurance.Builder clearPlan() {
      plan = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
     * Gets the value of the 'company' field.
     * @return The value.
     */
    public java.lang.String getCompany() {
      return company;
    }

    /**
     * Sets the value of the 'company' field.
     * @param value The value of 'company'.
     * @return This builder.
     */
    public com.example.streamdemo.domain.Insurance.Builder setCompany(java.lang.String value) {
      validate(fields()[1], value);
      this.company = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
     * Checks whether the 'company' field has been set.
     * @return True if the 'company' field has been set, false otherwise.
     */
    public boolean hasCompany() {
      return fieldSetFlags()[1];
    }


    /**
     * Clears the value of the 'company' field.
     * @return This builder.
     */
    public com.example.streamdemo.domain.Insurance.Builder clearCompany() {
      company = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
     * Gets the value of the 'validFrom' field.
     * @return The value.
     */
    public java.lang.String getValidFrom() {
      return validFrom;
    }

    /**
     * Sets the value of the 'validFrom' field.
     * @param value The value of 'validFrom'.
     * @return This builder.
     */
    public com.example.streamdemo.domain.Insurance.Builder setValidFrom(java.lang.String value) {
      validate(fields()[2], value);
      this.validFrom = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
     * Checks whether the 'validFrom' field has been set.
     * @return True if the 'validFrom' field has been set, false otherwise.
     */
    public boolean hasValidFrom() {
      return fieldSetFlags()[2];
    }


    /**
     * Clears the value of the 'validFrom' field.
     * @return This builder.
     */
    public com.example.streamdemo.domain.Insurance.Builder clearValidFrom() {
      validFrom = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
     * Gets the value of the 'age' field.
     * @return The value.
     */
    public java.lang.Integer getAge() {
      return age;
    }

    /**
     * Sets the value of the 'age' field.
     * @param value The value of 'age'.
     * @return This builder.
     */
    public com.example.streamdemo.domain.Insurance.Builder setAge(int value) {
      validate(fields()[3], value);
      this.age = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
     * Checks whether the 'age' field has been set.
     * @return True if the 'age' field has been set, false otherwise.
     */
    public boolean hasAge() {
      return fieldSetFlags()[3];
    }


    /**
     * Clears the value of the 'age' field.
     * @return This builder.
     */
    public com.example.streamdemo.domain.Insurance.Builder clearAge() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public Insurance build() {
      try {
        Insurance record = new Insurance();
        record.plan = fieldSetFlags()[0] ? this.plan : (java.lang.String) defaultValue(fields()[0]);
        record.company = fieldSetFlags()[1] ? this.company : (java.lang.String) defaultValue(fields()[1]);
        record.validFrom = fieldSetFlags()[2] ? this.validFrom : (java.lang.String) defaultValue(fields()[2]);
        record.age = fieldSetFlags()[3] ? this.age : (java.lang.Integer) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
      WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
      throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
      READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
      throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
